export interface PageExample {
  name: string;
  slug: string;
  titleKey: string;
  descKey: string;
}

// Keep this list unique by slug and alphabetized by name — the gallery index
// renders it verbatim. Guarded by pages-gallery.test.ts.
export const PAGES_EXAMPLES: PageExample[] = [
  {
    name: "About",
    slug: "about",
    titleKey: "aboutTitle",
    descKey: "aboutDescription",
  },
  {
    name: "Accept Invite",
    slug: "accept-invite",
    titleKey: "acceptInviteTitle",
    descKey: "acceptInviteDescription",
  },
  {
    name: "Address Book",
    slug: "address-book",
    titleKey: "addressBookTitle",
    descKey: "addressBookDescription",
  },
  {
    name: "Application Shell",
    slug: "application-shell",
    titleKey: "applicationShellTitle",
    descKey: "applicationShellDescription",
  },
  {
    name: "Awards",
    slug: "awards",
    titleKey: "awardsTitle",
    descKey: "awardsDescription",
  },
  {
    name: "Background Pattern",
    slug: "background-pattern",
    titleKey: "backgroundPatternTitle",
    descKey: "backgroundPatternDescription",
  },
  {
    name: "Banner",
    slug: "banner",
    titleKey: "bannerTitle",
    descKey: "bannerDescription",
  },
  {
    name: "Bento",
    slug: "bento",
    titleKey: "bentoTitle",
    descKey: "bentoDescription",
  },
  {
    name: "Blog",
    slug: "blog",
    titleKey: "blogTitle",
    descKey: "blogDescription",
  },
  {
    name: "Blog Post",
    slug: "blog-post",
    titleKey: "blogPostTitle",
    descKey: "blogPostDescription",
  },
  {
    name: "Book A Demo",
    slug: "book-a-demo",
    titleKey: "bookADemoTitle",
    descKey: "bookADemoDescription",
  },
  {
    name: "Careers",
    slug: "careers",
    titleKey: "careersTitle",
    descKey: "careersDescription",
  },
  {
    name: "Case Studies",
    slug: "case-studies",
    titleKey: "caseStudiesTitle",
    descKey: "caseStudiesDescription",
  },
  {
    name: "Case Study",
    slug: "case-study",
    titleKey: "caseStudyTitle",
    descKey: "caseStudyDescription",
  },
  {
    name: "Changelog",
    slug: "changelog",
    titleKey: "changelogTitle",
    descKey: "changelogDescription",
  },
  {
    name: "Chart Card",
    slug: "chart-card",
    titleKey: "chartCardTitle",
    descKey: "chartCardDescription",
  },
  {
    name: "Chart Group",
    slug: "chart-group",
    titleKey: "chartGroupTitle",
    descKey: "chartGroupDescription",
  },
  {
    name: "Checkout",
    slug: "checkout",
    titleKey: "checkoutTitle",
    descKey: "checkoutDescription",
  },
  {
    name: "Code Example",
    slug: "code-example",
    titleKey: "codeExampleTitle",
    descKey: "codeExampleDescription",
  },
  {
    name: "Community",
    slug: "community",
    titleKey: "communityTitle",
    descKey: "communityDescription",
  },
  {
    name: "Compare",
    slug: "compare",
    titleKey: "compareTitle",
    descKey: "compareDescription",
  },
  {
    name: "Compare Products",
    slug: "compare-products",
    titleKey: "compareProductsTitle",
    descKey: "compareProductsDescription",
  },
  {
    name: "Compliance",
    slug: "compliance",
    titleKey: "complianceTitle",
    descKey: "complianceDescription",
  },
  {
    name: "Contact",
    slug: "contact",
    titleKey: "contactTitle",
    descKey: "contactDescription",
  },
  {
    name: "Content",
    slug: "content",
    titleKey: "contentTitle",
    descKey: "contentDescription",
  },
  {
    name: "Cookie Banner",
    slug: "cookie-banner",
    titleKey: "cookieBannerTitle",
    descKey: "cookieBannerDescription",
  },
  {
    name: "Crud Companies",
    slug: "crud-companies",
    titleKey: "crudCompaniesTitle",
    descKey: "crudCompaniesDescription",
  },
  {
    name: "CTA",
    slug: "cta",
    titleKey: "ctaTitle",
    descKey: "ctaDescription",
  },
  {
    name: "Dashboard",
    slug: "dashboard",
    titleKey: "dashboardTitle",
    descKey: "dashboardDescription",
  },
  {
    name: "Data Table",
    slug: "data-table",
    titleKey: "dataTableTitle",
    descKey: "dataTableDescription",
  },
  {
    name: "Deals",
    slug: "deals",
    titleKey: "dealsTitle",
    descKey: "dealsDescription",
  },
  {
    name: "Download",
    slug: "download",
    titleKey: "downloadTitle",
    descKey: "downloadDescription",
  },
  {
    name: "Ecommerce Footer",
    slug: "ecommerce-footer",
    titleKey: "ecommerceFooterTitle",
    descKey: "ecommerceFooterDescription",
  },
  {
    name: "Ecommerce Hero",
    slug: "ecommerce-hero",
    titleKey: "ecommerceHeroTitle",
    descKey: "ecommerceHeroDescription",
  },
  {
    name: "Ecommerce Navbar",
    slug: "ecommerce-navbar",
    titleKey: "ecommerceNavbarTitle",
    descKey: "ecommerceNavbarDescription",
  },
  {
    name: "Experience",
    slug: "experience",
    titleKey: "experienceTitle",
    descKey: "experienceDescription",
  },
  {
    name: "FAQ",
    slug: "faq",
    titleKey: "faqTitle",
    descKey: "faqDescription",
  },
  {
    name: "Feature",
    slug: "feature",
    titleKey: "featureTitle",
    descKey: "featureDescription",
  },
  {
    name: "Feedback",
    slug: "feedback",
    titleKey: "feedbackTitle",
    descKey: "feedbackDescription",
  },
  {
    name: "Field Mapping",
    slug: "field-mapping",
    titleKey: "fieldMappingTitle",
    descKey: "fieldMappingDescription",
  },
  {
    name: "Footer",
    slug: "footer",
    titleKey: "footerTitle",
    descKey: "footerDescription",
  },
  {
    name: "Forgot Password",
    slug: "forgot-password",
    titleKey: "forgotPasswordTitle",
    descKey: "forgotPasswordDescription",
  },
  {
    name: "Gallery",
    slug: "gallery",
    titleKey: "galleryBlocksTitle",
    descKey: "galleryBlocksDescription",
  },
  {
    name: "Help",
    slug: "help",
    titleKey: "helpTitle",
    descKey: "helpDescription",
  },
  {
    name: "Help Center",
    slug: "help-center",
    titleKey: "helpCenterTitle",
    descKey: "helpCenterDescription",
  },
  {
    name: "Hero",
    slug: "hero",
    titleKey: "heroTitle",
    descKey: "heroDescription",
  },
  {
    name: "Incentives",
    slug: "incentives",
    titleKey: "incentivesTitle",
    descKey: "incentivesDescription",
  },
  {
    name: "Industries",
    slug: "industries",
    titleKey: "industriesTitle",
    descKey: "industriesDescription",
  },
  {
    name: "Integration",
    slug: "integration",
    titleKey: "integrationTitle",
    descKey: "integrationDescription",
  },
  {
    name: "Invite User",
    slug: "invite-user",
    titleKey: "inviteUserTitle",
    descKey: "inviteUserDescription",
  },
  {
    name: "Leaderboard",
    slug: "leaderboard",
    titleKey: "leaderboardTitle",
    descKey: "leaderboardDescription",
  },
  {
    name: "List",
    slug: "list",
    titleKey: "listTitle",
    descKey: "listDescription",
  },
  {
    name: "Live Purchase",
    slug: "live-purchase",
    titleKey: "livePurchaseTitle",
    descKey: "livePurchaseDescription",
  },
  {
    name: "Login",
    slug: "login",
    titleKey: "loginTitle",
    descKey: "loginDescription",
  },
  {
    name: "Logos",
    slug: "logos",
    titleKey: "logosTitle",
    descKey: "logosDescription",
  },
  {
    name: "Magic Link",
    slug: "magic-link",
    titleKey: "magicLinkTitle",
    descKey: "magicLinkDescription",
  },
  {
    name: "Navbar",
    slug: "navbar",
    titleKey: "navbarTitle",
    descKey: "navbarDescription",
  },
  {
    name: "Newsletter",
    slug: "newsletter",
    titleKey: "newsletterTitle",
    descKey: "newsletterDescription",
  },
  {
    name: "Offer Modal",
    slug: "offer-modal",
    titleKey: "offerModalTitle",
    descKey: "offerModalDescription",
  },
  {
    name: "Onboarding",
    slug: "onboarding",
    titleKey: "onboardingTitle",
    descKey: "onboardingDescription",
  },
  {
    name: "Order History",
    slug: "order-history",
    titleKey: "orderHistoryTitle",
    descKey: "orderHistoryDescription",
  },
  {
    name: "Order Summary",
    slug: "order-summary",
    titleKey: "orderSummaryTitle",
    descKey: "orderSummaryDescription",
  },
  {
    name: "Our Story",
    slug: "our-story",
    titleKey: "ourStoryTitle",
    descKey: "ourStoryDescription",
  },
  {
    name: "Passkey",
    slug: "passkey",
    titleKey: "passkeyTitle",
    descKey: "passkeyDescription",
  },
  {
    name: "Payment Methods",
    slug: "payment-methods",
    titleKey: "paymentMethodsTitle",
    descKey: "paymentMethodsDescription",
  },
  {
    name: "Pricing",
    slug: "pricing",
    titleKey: "pricingTitle",
    descKey: "pricingDescription",
  },
  {
    name: "Process",
    slug: "process",
    titleKey: "processTitle",
    descKey: "processDescription",
  },
  {
    name: "Product Card",
    slug: "product-card",
    titleKey: "productCardTitle",
    descKey: "productCardDescription",
  },
  {
    name: "Product Categories",
    slug: "product-categories",
    titleKey: "productCategoriesTitle",
    descKey: "productCategoriesDescription",
  },
  {
    name: "Product Detail",
    slug: "product-detail",
    titleKey: "productDetailTitle",
    descKey: "productDetailDescription",
  },
  {
    name: "Product Gallery",
    slug: "product-gallery",
    titleKey: "productGalleryTitle",
    descKey: "productGalleryDescription",
  },
  {
    name: "Product List",
    slug: "product-list",
    titleKey: "productListTitle",
    descKey: "productListDescription",
  },
  {
    name: "Product Quick View",
    slug: "product-quick-view",
    titleKey: "productQuickViewTitle",
    descKey: "productQuickViewDescription",
  },
  {
    name: "Product Search",
    slug: "product-search",
    titleKey: "productSearchTitle",
    descKey: "productSearchDescription",
  },
  {
    name: "Product Specs",
    slug: "product-specs",
    titleKey: "productSpecsTitle",
    descKey: "productSpecsDescription",
  },
  {
    name: "Project",
    slug: "project",
    titleKey: "projectTitle",
    descKey: "projectDescription",
  },
  {
    name: "Projects",
    slug: "projects",
    titleKey: "projectsTitle",
    descKey: "projectsDescription",
  },
  {
    name: "Promo Banner",
    slug: "promo-banner",
    titleKey: "promoBannerTitle",
    descKey: "promoBannerDescription",
  },
  {
    name: "Rate Card",
    slug: "rate-card",
    titleKey: "rateCardTitle",
    descKey: "rateCardDescription",
  },
  {
    name: "Reset Password",
    slug: "reset-password",
    titleKey: "resetPasswordTitle",
    descKey: "resetPasswordDescription",
  },
  {
    name: "Resource",
    slug: "resource",
    titleKey: "resourceTitle",
    descKey: "resourceDescription",
  },
  {
    name: "Resources",
    slug: "resources",
    titleKey: "resourcesTitle",
    descKey: "resourcesDescription",
  },
  {
    name: "Reviews",
    slug: "reviews",
    titleKey: "reviewsTitle",
    descKey: "reviewsDescription",
  },
  {
    name: "Service",
    slug: "service",
    titleKey: "serviceTitle",
    descKey: "serviceDescription",
  },
  {
    name: "Services",
    slug: "services",
    titleKey: "servicesTitle",
    descKey: "servicesDescription",
  },
  {
    name: "Settings Integrations",
    slug: "settings-integrations",
    titleKey: "settingsIntegrationsTitle",
    descKey: "settingsIntegrationsDescription",
  },
  {
    name: "Settings Members",
    slug: "settings-members",
    titleKey: "settingsMembersTitle",
    descKey: "settingsMembersDescription",
  },
  {
    name: "Settings Notifications",
    slug: "settings-notifications",
    titleKey: "settingsNotificationsTitle",
    descKey: "settingsNotificationsDescription",
  },
  {
    name: "Settings Profile",
    slug: "settings-profile",
    titleKey: "settingsProfileTitle",
    descKey: "settingsProfileDescription",
  },
  {
    name: "Shader",
    slug: "shader",
    titleKey: "shaderTitle",
    descKey: "shaderDescription",
  },
  {
    name: "Shopping Cart",
    slug: "shopping-cart",
    titleKey: "shoppingCartTitle",
    descKey: "shoppingCartDescription",
  },
  {
    name: "Shop The Look",
    slug: "shop-the-look",
    titleKey: "shopTheLookTitle",
    descKey: "shopTheLookDescription",
  },
  {
    name: "Sidebar",
    slug: "sidebar",
    titleKey: "sidebarTitle",
    descKey: "sidebarDescription",
  },
  {
    name: "Signup",
    slug: "signup",
    titleKey: "signupTitle",
    descKey: "signupDescription",
  },
  {
    name: "Skills",
    slug: "skills",
    titleKey: "skillsTitle",
    descKey: "skillsDescription",
  },
  {
    name: "Social Media Trending",
    slug: "social-media-trending",
    titleKey: "socialMediaTrendingTitle",
    descKey: "socialMediaTrendingDescription",
  },
  {
    name: "Stats",
    slug: "stats",
    titleKey: "statsTitle",
    descKey: "statsDescription",
  },
  {
    name: "Stats Card",
    slug: "stats-card",
    titleKey: "statsCardTitle",
    descKey: "statsCardDescription",
  },
  {
    name: "Team",
    slug: "team",
    titleKey: "teamTitle",
    descKey: "teamDescription",
  },
  {
    name: "Testimonial",
    slug: "testimonial",
    titleKey: "testimonialTitle",
    descKey: "testimonialDescription",
  },
  {
    name: "Timeline",
    slug: "timeline",
    titleKey: "timelineTitle",
    descKey: "timelineDescription",
  },
  {
    name: "Todo List",
    slug: "todo-list",
    titleKey: "todoListTitle",
    descKey: "todoListDescription",
  },
  {
    name: "Trust Strip",
    slug: "trust-strip",
    titleKey: "trustStripTitle",
    descKey: "trustStripDescription",
  },
  {
    name: "Two Factor",
    slug: "two-factor",
    titleKey: "twoFactorTitle",
    descKey: "twoFactorDescription",
  },
  {
    name: "User Profile",
    slug: "user-profile",
    titleKey: "userProfileTitle",
    descKey: "userProfileDescription",
  },
  {
    name: "Verify Email",
    slug: "verify-email",
    titleKey: "verifyEmailTitle",
    descKey: "verifyEmailDescription",
  },
  {
    name: "Waitlist",
    slug: "waitlist",
    titleKey: "waitlistTitle",
    descKey: "waitlistDescription",
  },
  {
    name: "Wishlist",
    slug: "wishlist",
    titleKey: "wishlistTitle",
    descKey: "wishlistDescription",
  },
];
