// Registry of every ui demo page. Consumed by the /v1/:lang/ui gallery and
// by e2e/ui-smoke.spec.ts + e2e/ui-a11y.spec.ts — adding a page here puts it
// in the gallery and under the smoke/axe walk in the same edit.
export const UI_COMPONENTS = [
  { name: "Accordion", slug: "accordion" },
  { name: "Alert", slug: "alert" },
  { name: "Alert Dialog", slug: "alert-dialog" },
  { name: "Aspect Ratio", slug: "aspect-ratio" },
  { name: "Avatar", slug: "avatar" },
  { name: "Badge", slug: "badge" },
  { name: "Breadcrumb", slug: "breadcrumb" },
  { name: "Button", slug: "button" },
  { name: "Calendar", slug: "calendar" },
  { name: "Card", slug: "card" },
  { name: "Carousel", slug: "carousel" },
  { name: "Checkbox", slug: "checkbox" },
  { name: "Collapsible", slug: "collapsible" },
  { name: "Combobox", slug: "combobox" },
  { name: "Command", slug: "command" },
  { name: "Confirm Dialog", slug: "confirm-dialog" },
  { name: "Context Menu", slug: "context-menu" },
  { name: "Counter", slug: "counter" },
  { name: "Date Picker", slug: "date-picker" },
  { name: "Dialog", slug: "dialog" },
  { name: "Drawer", slug: "drawer" },
  { name: "Dropdown", slug: "dropdown" },
  { name: "Dropdown Menu", slug: "dropdown-menu" },
  { name: "Empty", slug: "empty" },
  { name: "Form Error Banner", slug: "form-error-banner" },
  { name: "Form Field Info", slug: "form-field-info" },
  { name: "File Upload", slug: "file-upload" },
  { name: "Error Boundary", slug: "error-boundary" },
  { name: "Hover Card", slug: "hover-card" },
  { name: "Image Upload", slug: "image-upload" },
  { name: "Input Group", slug: "input-group" },
  { name: "Input OTP", slug: "input-otp" },
  { name: "Kbd", slug: "kbd" },
  { name: "Label", slug: "label" },
  { name: "Logo Spinner", slug: "logo-spinner" },
  { name: "Menubar", slug: "menubar" },
  { name: "Native Select", slug: "native-select" },
  { name: "Navigation Menu", slug: "navigation-menu" },
  { name: "Pagination", slug: "pagination" },
  { name: "Popover", slug: "popover" },
  { name: "Progress", slug: "progress" },
  { name: "Radio Group", slug: "radio-group" },
  { name: "Resizable", slug: "resizable" },
  { name: "Scroll Area", slug: "scroll-area" },
  { name: "Scroll To Bottom Button", slug: "scroll-to-bottom-button" },
  { name: "Select", slug: "select" },
  { name: "Separator", slug: "separator" },
  { name: "Sheet", slug: "sheet" },
  { name: "Skeleton", slug: "skeleton" },
  { name: "Slider", slug: "slider" },
  { name: "Spinner", slug: "spinner" },
  { name: "Step Indicator", slug: "step-indicator" },
  { name: "Switch", slug: "switch" },
  { name: "Tabs", slug: "tabs" },
  { name: "Textarea", slug: "textarea" },
  { name: "Time Input", slug: "time-input" },
  { name: "Toast", slug: "toast" },
  { name: "Toggle", slug: "toggle" },
  { name: "Toggle Group", slug: "toggle-group" },
  { name: "Tooltip", slug: "tooltip" },
  { name: "Typography", slug: "typography" },
] as const;

export type UIComponentSlug = (typeof UI_COMPONENTS)[number]["slug"];
