export type ExceptionCode =
  | 'EX_VALIDATION_FORM'
  | 'EX_AUTH_INVALID_CREDENTIALS'
  | 'EX_AUTH_EMAIL_TAKEN'
  | 'EX_AUTH_ACCOUNT_LOCKED'
  | 'EX_CONFLICT_DUPLICATE'
  | 'EX_CONFLICT_FOREIGN_KEY'
  | 'EX_CONFLICT_RELATION'
  | 'EX_INCONSISTENT_DATA'
  | 'EX_NOT_FOUND'
  | 'EX_FORBIDDEN'
  | 'EX_WS_UNSTABLE'
  | 'EX_TIER_INSUFFICIENT'
  | 'EX_INTERNAL';
