/**
 * Generates the pages-gallery source pipeline consumed by the template
 * browser (`src/views/pages/_shared/`):
 *
 * - `src/generated/pages-manifest.ts` — per category, the ordered list of
 *   variant ids with the view file each one renders (parsed from that
 *   category's `PageContent.tsx`), used for variant counts and code lookup.
 * - `src/generated/pages-sources/<category>.ts` — variant id → raw TSX
 *   source, one lazily-imported module per category so no source text ever
 *   reaches the eager bundle.
 * - `src/generated/pages-sources/index.ts` — static dynamic-import map so
 *   both bundlers (turbopack + vite) can code-split per category.
 *
 * Run via: `pnpm generate-pages-sources` (also part of `prebuild`).
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pagesRoot = join(__dirname, "..", "src", "views", "pages");
const outManifest = join(
  __dirname,
  "..",
  "src",
  "generated",
  "pages-manifest.ts",
);
const outSourcesDir = join(
  __dirname,
  "..",
  "src",
  "generated",
  "pages-sources",
);

interface Entry {
  id: string;
  file: string;
}

const HEADER =
  "// AUTO-GENERATED by scripts/generate-pages-sources.ts — do not edit.\n" +
  "// Regenerate with `pnpm generate-pages-sources`.\n";

function categories(): string[] {
  return readdirSync(pagesRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith("_"))
    .map((d) => d.name)
    .sort();
}

function parseEntries(category: string): Entry[] {
  const pageContent = readFileSync(
    join(pagesRoot, category, "PageContent.tsx"),
    "utf8",
  );
  const entryRe =
    /id:\s*"([^"]+)"[\s\S]*?render:\s*\(\)\s*=>\s*<([A-Za-z][A-Za-z0-9_]*)/g;
  const entries: Entry[] = [];
  for (const match of pageContent.matchAll(entryRe)) {
    entries.push({ id: match[1], file: `${category}/${match[2]}.tsx` });
  }

  const renderCount = (pageContent.match(/render:\s*\(\)\s*=>/g) ?? []).length;
  if (entries.length !== renderCount) {
    throw new Error(
      `${category}/PageContent.tsx: parsed ${entries.length} entries but found ` +
        `${renderCount} render callbacks — the id/render pattern changed; update this script.`,
    );
  }
  const ids = new Set(entries.map((e) => e.id));
  if (ids.size !== entries.length) {
    throw new Error(`${category}/PageContent.tsx: duplicate variant ids.`);
  }
  for (const entry of entries) {
    if (!existsSync(join(pagesRoot, entry.file))) {
      throw new Error(
        `${category}/PageContent.tsx: variant "${entry.id}" renders a component ` +
          `with no matching file at views/pages/${entry.file}.`,
      );
    }
  }
  return entries;
}

function generate(): void {
  mkdirSync(outSourcesDir, { recursive: true });
  const manifest: Record<string, Entry[]> = {};
  let variantTotal = 0;

  for (const category of categories()) {
    const entries = parseEntries(category);
    manifest[category] = entries;
    variantTotal += entries.length;

    const sources: Record<string, string> = {};
    for (const entry of entries) {
      sources[entry.id] = readFileSync(join(pagesRoot, entry.file), "utf8");
    }
    const sourcesModule =
      HEADER +
      "const sources: Record<string, string> = " +
      JSON.stringify(sources, null, 0) +
      ";\nexport default sources;\n";
    writeFileSync(join(outSourcesDir, `${category}.ts`), sourcesModule);
  }

  const manifestModule =
    HEADER +
    "export interface PagesManifestEntry {\n  id: string;\n  file: string;\n}\n\n" +
    "export const PAGES_MANIFEST: Record<string, readonly PagesManifestEntry[]> = " +
    JSON.stringify(manifest, null, 2) +
    ";\n";
  writeFileSync(outManifest, manifestModule);

  const loaders =
    HEADER +
    "type SourcesModule = { default: Record<string, string> };\n\n" +
    "export const sourceLoaders: Record<string, () => Promise<SourcesModule>> = {\n" +
    Object.keys(manifest)
      .map((category) => `  "${category}": () => import("./${category}"),`)
      .join("\n") +
    "\n};\n";
  writeFileSync(join(outSourcesDir, "index.ts"), loaders);

  console.log(
    `✓ Wrote ${outManifest} (${Object.keys(manifest).length} categories, ${variantTotal} variants)`,
  );
  console.log(`✓ Wrote ${outSourcesDir}/*.ts`);
}

generate();
