import 'package:flutter/material.dart';

Map<String, IconData> formIcons = {
  'person': Icons.person_outline,
  'email': Icons.email_outlined,
  'lock': Icons.lock_outline,
  'phone': Icons.phone_outlined,
  'home': Icons.home_outlined,
  'search': Icons.search,
  'calendar': Icons.calendar_today_outlined,
  'map': Icons.map_outlined,
  'card': Icons.credit_card_outlined,
  'upload': Icons.cloud_upload_outlined,
  'image': Icons.image_outlined,
  'file': Icons.insert_drive_file_outlined,
  'settings': Icons.settings_outlined,
  'info': Icons.info_outline,
  'warning': Icons.warning_amber_outlined,
  'check': Icons.check_circle_outline,
  'close': Icons.close,
  'arrow_down': Icons.keyboard_arrow_down,
  'arrow_right': Icons.chevron_right,
  'edit': Icons.edit_outlined,
  'delete': Icons.delete_outline,
  'add': Icons.add_circle_outline,
  'remove': Icons.remove_circle_outline,
  'visibility': Icons.visibility_outlined,
  'visibility_off': Icons.visibility_off_outlined,
};
