apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: nest-backend:latest
          command:
            - node_modules/.bin/prisma
          args:
            - db
            - push
            - --accept-data-loss
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
