import {
  BadRequestException,
  Controller,
  Get,
  HttpStatus,
  Logger,
  Param,
  Query,
  Redirect,
  Res,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Response } from 'express';
import { AuthService } from '../auth.service';
import { OAuthService } from './oauth.service';

// URL.origin is the opaque string "null" for non-special schemes (custom app URI
// schemes like "flutterboilerplate://"), so it can never match a real origin —
// compare scheme+host directly instead, which works for both http(s) and custom
// schemes.
function redirectOrigin(url: URL): string {
  return `${url.protocol}//${url.host}`;
}

function isSafeRedirect(target: string, allowedOrigins: string[]): boolean {
  try {
    return allowedOrigins.includes(redirectOrigin(new URL(target)));
  } catch {
    return false;
  }
}

@Controller('auth/oauth')
export class OAuthController {
  private readonly logger = new Logger(OAuthController.name);

  constructor(
    private readonly oauth: OAuthService,
    private readonly auth: AuthService,
    private readonly config: ConfigService,
  ) {}

  private get frontendOrigin(): string {
    return this.config
      .get<string>('FRONTEND_URL', 'http://localhost:3000')
      .replace(/\/+$/, '');
  }

  /** Custom URI scheme the Flutter app registers for its OAuth deep-link callback. */
  private get mobileRedirectOrigin(): string {
    return this.config
      .get<string>('MOBILE_OAUTH_REDIRECT_ORIGIN', 'flutterboilerplate://oauth')
      .replace(/\/+$/, '');
  }

  private get allowedRedirectOrigins(): string[] {
    return [this.frontendOrigin, this.mobileRedirectOrigin];
  }

  /**
   * GET /auth/oauth/:provider — initiate OAuth flow.
   * Redirects to the provider's authorization page.
   * Query params:
   *   state — CSRF token (generated by Next.js BFF, required)
   *   redirect_uri — where NestJS should redirect back after OAuth (Next.js callback URL)
   */
  @Get(':provider')
  @Redirect()
  async initiate(
    @Param('provider') provider: string,
    @Query('state') state: string,
    @Query('redirect_uri') redirectUri: string,
  ) {
    if (!state || !redirectUri) {
      throw new BadRequestException({
        exc: 'EX_VALIDATION_FORM',
        msg: 'Missing state or redirect_uri parameter',
        key: 'error.missingOAuthParams',
      });
    }
    if (!isSafeRedirect(redirectUri, this.allowedRedirectOrigins)) {
      throw new BadRequestException({
        exc: 'EX_VALIDATION_FORM',
        msg: 'Invalid redirect_uri origin',
        key: 'error.invalidRedirectUri',
      });
    }
    const url = await this.oauth.buildAuthUrl(provider, state, redirectUri);
    return { url, statusCode: HttpStatus.FOUND };
  }

  /**
   * GET /auth/oauth/:provider/callback — OAuth provider callback.
   * Exchanges the code, fetches the profile, stores it, and redirects
   * back to the Next.js callback URL with ?state=.. so the BFF can
   * retrieve the profile.
   */
  @Get(':provider/callback')
  async callback(
    @Param('provider') provider: string,
    @Query('code') code: string,
    @Query('state') state: string,
    @Query('error') error: string,
    @Res({ passthrough: true }) res: Response,
  ) {
    const redirectUriForState = state
      ? await this.oauth.getRedirectUri(state)
      : null;
    const safeLoginErrorUrl = (err: string) => {
      let origin = this.frontendOrigin;
      if (redirectUriForState) {
        try {
          const candidate = redirectOrigin(new URL(redirectUriForState));
          if (this.allowedRedirectOrigins.includes(candidate)) {
            origin = candidate;
          }
        } catch {
          // keep frontendOrigin fallback
        }
      }
      return `${origin}/auth/login?error=${encodeURIComponent(err)}`;
    };

    if (error) {
      return res.redirect(HttpStatus.FOUND, safeLoginErrorUrl(error));
    }
    if (!code || !state) {
      return res.redirect(
        HttpStatus.FOUND,
        safeLoginErrorUrl('missing_params'),
      );
    }

    try {
      const redirectUri = await this.oauth.handleCallback(code, state);
      const safeTarget = isSafeRedirect(
        redirectUri,
        this.allowedRedirectOrigins,
      )
        ? redirectUri
        : this.frontendOrigin;
      const separator = safeTarget.includes('?') ? '&' : '?';
      return res.redirect(
        HttpStatus.FOUND,
        `${safeTarget}${separator}state=${encodeURIComponent(state)}`,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'unknown';
      this.logger.error(`OAuth callback failed for ${provider}: ${msg}`);
      return res.redirect(HttpStatus.FOUND, safeLoginErrorUrl(msg));
    }
  }
}
