import {
  BadRequestException,
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Logger,
  Param,
  Query,
  Redirect,
  Res,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Response } from 'express';
import { AuthService } from '../auth.service';
import { OAuthService } from './oauth.service';

@Controller('auth/oauth')
export class OAuthController {
  private readonly logger = new Logger(OAuthController.name);

  constructor(
    private readonly oauth: OAuthService,
    private readonly auth: AuthService,
    private readonly config: ConfigService,
  ) {}

  /** GET /auth/oauth/providers — returns list of configured provider names */
  @Get('providers')
  listProviders() {
    return this.oauth.getConfiguredProviders();
  }

  /**
   * GET /auth/oauth/:provider — initiate OAuth flow.
   * Redirects to the provider's authorization page.
   * Query params:
   *   state — CSRF token (generated by Next.js BFF, required)
   *   redirect_uri — where NestJS should redirect back after OAuth (Next.js callback URL)
   */
  @Get(':provider')
  @Redirect()
  initiate(
    @Param('provider') provider: string,
    @Query('state') state: string,
    @Query('redirect_uri') redirectUri: string,
  ) {
    if (!state || !redirectUri) {
      throw new BadRequestException({
        exc: 'EX_VALIDATION_FORM',
        msg: 'Missing state or redirect_uri parameter',
        key: 'error.missingOAuthParams',
      });
    }
    const url = this.oauth.buildAuthUrl(provider, state, redirectUri);
    return { url, statusCode: HttpStatus.FOUND };
  }

  /**
   * GET /auth/oauth/:provider/callback — OAuth provider callback.
   * Exchanges the code, fetches the profile, stores it, and redirects
   * back to the Next.js callback URL with ?state=.. so the BFF can
   * retrieve the profile.
   */
  @Get(':provider/callback')
  async callback(
    @Param('provider') provider: string,
    @Query('code') code: string,
    @Query('state') state: string,
    @Query('error') error: string,
    @Res({ passthrough: true }) res: Response,
  ) {
    const frontendOrigin = this.config
      .get<string>('FRONTEND_URL', 'http://localhost:3000')
      .replace(/\/+$/, '');
    const loginErrorUrl = (err: string) => {
      const origin = state
        ? new URL(this.oauth.getRedirectUri(state) ?? frontendOrigin).origin
        : frontendOrigin;
      return `${origin}/auth/login?error=${encodeURIComponent(err)}`;
    };

    if (error) {
      return res.redirect(HttpStatus.FOUND, loginErrorUrl(error));
    }
    if (!code || !state) {
      return res.redirect(HttpStatus.FOUND, loginErrorUrl('missing_params'));
    }

    try {
      const redirectUri = await this.oauth.handleCallback(code, state);
      const separator = redirectUri.includes('?') ? '&' : '?';
      return res.redirect(
        HttpStatus.FOUND,
        `${redirectUri}${separator}state=${encodeURIComponent(state)}`,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'unknown';
      this.logger.error(`OAuth callback failed for ${provider}: ${msg}`);
      return res.redirect(HttpStatus.FOUND, loginErrorUrl(msg));
    }
  }

  /**
   * GET /auth/oauth/:provider/profile — retrieve the OAuth profile
   * that was stored during the callback, using the state as key.
   */
  @Get(':provider/profile')
  @HttpCode(HttpStatus.OK)
  getProfile(@Query('state') state: string) {
    return this.oauth.retrieveProfile(state);
  }
}
